# Generated by Django 6.0.6 on 2026-06-22 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=150)),
                ('archivo', models.FileField(upload_to='datasets_csv/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_algoritmo', models.CharField(choices=[('NB', 'Naive Bayes'), ('KNN', 'k-Nearest Neighbors')], max_length=3)),
                ('parametro_k', models.IntegerField(blank=True, null=True)),
                ('fecha_entrenamiento', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.dataset')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_local', models.CharField(max_length=100)),
                ('equipo_visitante', models.CharField(max_length=100)),
                ('prob_local', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prob_empate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prob_visitante', models.DecimalField(decimal_places=2, max_digits=5)),
                ('resultado_predicho', models.CharField(choices=[('1', 'Victoria Local'), ('X', 'Empate'), ('2', 'Victoria Visitante')], max_length=1)),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.modeloml')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidad_combinada', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('predicciones', models.ManyToManyField(to='web.prediccion')),
            ],
        ),
    ]
