# Generated by Django 6.0.6 on 2026-06-22 17:29

import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediccion',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='parley',
            name='predicciones',
        ),
        migrations.RemoveField(
            model_name='parley',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='prediccion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='dataset',
            name='algoritmo',
            field=models.CharField(choices=[('NB', 'Naive Bayes'), ('KNN', 'k-Nearest Neighbors')], default='KNN', max_length=3),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='archivo',
            field=models.FileField(upload_to=web.models.ruta_guardado_dataset),
        ),
        migrations.DeleteModel(
            name='ModeloML',
        ),
        migrations.DeleteModel(
            name='Parley',
        ),
        migrations.DeleteModel(
            name='Prediccion',
        ),
    ]
